"""Renders the weekly report as Markdown (or HTML) and optionally emails it."""
from __future__ import annotations

import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from .config import env
from .db import Item
from . import summarizer

MD_TEMPLATE = """# {{ industry }} — Weekly Briefing
_{{ date_range }}_

{% if personalized_lines %}
## 🔔 For you specifically
{{ personalized_lines }}

{% endif %}
## 📄 arXiv research
{{ arxiv_summary }}

{{ arxiv_lines }}

## 📰 News
{{ news_summary }}

{{ news_lines }}

## 🎤 Conferences & industry events
{{ conference_lines }}

## 💼 LinkedIn (manual)
{{ linkedin_lines }}

---
_Generated by besseleth on {{ generated_at }}. {{ item_count }} items scanned this week._
"""


def _md_link_lines(items: list[Item]) -> str:
    return "\n".join(f"- [{i.title}]({i.url})" for i in items) or "_None this week._"


def _render_markdown(context: dict) -> str:
    from jinja2 import Template

    return Template(MD_TEMPLATE, trim_blocks=True, lstrip_blocks=True).render(**context)


def build_report(
    industry_name: str,
    days_back: int,
    arxiv_items: list[Item],
    news_items: list[Item],
    conference_items: list[Item],
    linkedin_items: list[Item],
    personalized_items: list[Item],
    summarizer_cfg: dict,
) -> tuple[str, str]:
    """Returns (report_id, rendered_markdown)."""
    now = datetime.now(timezone.utc)
    report_id = now.strftime("%Y-%m-%d")
    date_range = f"{(now).strftime('%b %d, %Y')} (last {days_back} days)"

    arxiv_summary = summarizer.summarize_section(arxiv_items, "arXiv research", industry_name, summarizer_cfg)
    news_summary = summarizer.summarize_section(news_items, "News", industry_name, summarizer_cfg)

    personalized_lines = "\n".join(
        (
            f"- **{item.title}** — {summarizer.summarize_item(item, summarizer_cfg)}\n"
            f"  _Relevant because **{item.matched_contact}** works at **{item.matched_company}**._"
            + (f" [link]({item.url})" if item.url else "")
        )
        for item in personalized_items
    )

    conference_lines = "\n".join(
        f"- **{item.title}** — {item.summary}" + (f" ([info]({item.url}))" if item.url else "")
        for item in conference_items
    ) or "_None on the watchlist this month._"

    linkedin_lines = "\n".join(
        f"- **{item.title}** — {item.summary[:200]}" + (f" ([link]({item.url}))" if item.url else "")
        for item in linkedin_items
    ) or "_Nothing pasted this week. Drop LinkedIn posts/listings into linkedin_drops/ or run `linkedin-add`._"

    context = {
        "industry": industry_name,
        "date_range": date_range,
        "personalized_lines": personalized_lines,
        "arxiv_summary": arxiv_summary or "No new arXiv papers matched this week.",
        "arxiv_lines": _md_link_lines(arxiv_items),
        "news_summary": news_summary or "No notable news this week.",
        "news_lines": _md_link_lines(news_items),
        "conference_lines": conference_lines,
        "linkedin_lines": linkedin_lines,
        "generated_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "item_count": len(arxiv_items) + len(news_items) + len(conference_items) + len(linkedin_items),
    }
    return report_id, _render_markdown(context)


def save_report(markdown: str, report_id: str, output_dir: str) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"report-{report_id}.md"
    path.write_text(markdown)
    return path


def email_report(markdown: str, report_id: str, industry_name: str, email_cfg: dict):
    if not email_cfg.get("enabled"):
        return
    user = env(email_cfg.get("smtp_user_env", ""))
    password = env(email_cfg.get("smtp_pass_env", ""))
    to = email_cfg.get("to", [])
    if not (user and password and to):
        print("[report] Email enabled but SMTP creds or recipients missing; skipping send.")
        return

    msg = MIMEMultipart()
    msg["From"] = user
    msg["To"] = ", ".join(to)
    msg["Subject"] = f"{industry_name} Weekly Briefing — {report_id}"
    msg.attach(MIMEText(markdown, "plain"))

    try:
        with smtplib.SMTP(email_cfg["smtp_host"], email_cfg["smtp_port"]) as server:
            server.starttls()
            server.login(user, password)
            server.sendmail(user, to, msg.as_string())
        print(f"[report] Emailed to {to}")
    except Exception as e:
        print(f"[report] Failed to send email: {e}")
