"""Renders the weekly report as Markdown (or HTML) and optionally emails it."""
from __future__ import annotations

import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from .config import env
from .db import Item
from . import summarizer

MD_TEMPLATE = """# {{ industry }} — Weekly Briefing
_{{ date_range }}_

{% if personalized_lines %}
## 🔔 For you
{{ personalized_lines }}

{% endif %}
## 📄 arXiv research
{{ arxiv_summary }}

## 📰 News
{{ news_summary }}

## ✍️ Blogs
{{ blog_summary }}

## 🎤 Conferences & industry events
{{ conference_lines }}

{% if conference_news_lines %}
### Conference news (talks, CFPs, announcements)
{{ conference_news_lines }}

{% endif %}
## 📍 Events near you
{{ event_lines }}

## 💬 Social (Bluesky / X)
{{ social_lines }}

## 💼 LinkedIn (manual)
{{ linkedin_lines }}

{% if clip_lines %}
## 📌 Clipped (pasted, source not auto-recognized)
{{ clip_lines }}

{% endif %}
{% if context_summary %}
## 🧠 Big picture
{{ context_summary }}

{% endif %}
---
_Generated by besseleth on {{ generated_at }}. {{ item_count }} items scanned this week._
"""


def _snippet_lines(items: list[Item], max_chars: int = 200) -> str:
    return "\n".join(
        f"- **{i.title}** — {i.summary[:max_chars]}" + (f" ([link]({i.url}))" if i.url else "")
        for i in items
    ) or "_None this week._"


def _linkedin_lines(items: list[Item], summarizer_cfg: dict) -> str:
    """Just the basics (role, company, location) per pasted post, not the
    raw pasted text — see summarizer.summarize_linkedin_item's docstring."""
    return "\n".join(
        f"- **{summarizer.summarize_linkedin_item(i, summarizer_cfg)}**" + (f" ([link]({i.url}))" if i.url else "")
        for i in items
    ) or "_None this week._"


def _render_markdown(context: dict) -> str:
    from jinja2 import Template

    return Template(MD_TEMPLATE, trim_blocks=True, lstrip_blocks=True).render(**context)


def build_report(
    industry_name: str,
    days_back: int,
    arxiv_items: list[Item],
    news_items: list[Item],
    blog_items: list[Item],
    conference_items: list[Item],
    conference_news_items: list[Item],
    event_items: list[Item],
    social_items: list[Item],
    linkedin_items: list[Item],
    personalized_items: list[Item],
    summarizer_cfg: dict,
    clip_items: list[Item] | None = None,
    history: dict | None = None,
) -> tuple[str, str]:
    """Returns (report_id, rendered_markdown). `history` (from
    DB.accumulated_knowledge_stats()) is everything besseleth knows from
    every past run, not just this one — used only for the closing 'Big
    picture' section, so a fresh, independent report doesn't need any
    other item from a previous report to render correctly.

    report_id includes the time (not just the date) so two runs on the
    same day — someone hits "Run now" twice, or pastes something new
    right after a scheduled run — each get their own report file instead
    of the second one silently overwriting the first."""
    clip_items = clip_items or []
    history = history or {}
    now = datetime.now(timezone.utc)
    report_id = now.strftime("%Y-%m-%d-%H%M%S")
    date_range = f"{(now).strftime('%b %d, %Y')} (last {days_back} days)"

    # Bulleted, one sentence + a numbered citation per item — assigned in
    # code from the item's position, never trusted to an LLM citing many
    # items in one combined call (which is what was dropping links
    # entirely for some items). See summarize_items_numbered's docstring.
    arxiv_summary = summarizer.summarize_items_numbered(arxiv_items, industry_name, summarizer_cfg)
    news_summary = summarizer.summarize_items_numbered(news_items, industry_name, summarizer_cfg)
    blog_summary = summarizer.summarize_section(blog_items, "Blogs", industry_name, summarizer_cfg)

    def _relevance_tag(item: Item) -> str:
        # matched_contact/matched_company always come straight from your
        # own contacts.yaml/config.yaml entry, never a placeholder — so
        # this already renders whoever you actually added.
        if item.matched_reason == "interest":
            return f"_Matches your interest in **{item.matched_company}**._"
        if item.matched_reason == "school":
            return f"_Relevant because **{item.matched_contact}** went to **{item.matched_company}**._"
        return f"_Relevant because **{item.matched_contact}** works at **{item.matched_company}**._"

    personalized_lines = "\n".join(
        f"- **{item.title}**" + (f" [{i}]({item.url})" if item.url else "") + f"\n  {_relevance_tag(item)}"
        for i, item in enumerate(personalized_items, start=1)
    )

    conference_lines = "\n".join(
        f"- **{item.title}** — {item.summary}" + (f" ([info]({item.url}))" if item.url else "")
        for item in conference_items
    ) or "_None on the watchlist this month._"

    all_new_items = [
        *arxiv_items,
        *news_items,
        *blog_items,
        *conference_items,
        *conference_news_items,
        *event_items,
        *social_items,
        *linkedin_items,
        *clip_items,
    ]
    context_summary = summarizer.summarize_context(all_new_items, history, industry_name, summarizer_cfg)

    context = {
        "industry": industry_name,
        "date_range": date_range,
        "personalized_lines": personalized_lines,
        "arxiv_summary": arxiv_summary or "No new arXiv papers matched this week.",
        "news_summary": news_summary or "No notable news this week.",
        "blog_summary": blog_summary or "No notable blog posts this week.",
        "conference_lines": conference_lines,
        "conference_news_lines": _snippet_lines(conference_news_items) if conference_news_items else "",
        "event_lines": _snippet_lines(event_items),
        "social_lines": _snippet_lines(social_items),
        "linkedin_lines": _linkedin_lines(linkedin_items, summarizer_cfg)
        if linkedin_items
        else "_Nothing pasted this week. Use the dashboard's Paste tab, or `linkedin-add`._",
        "clip_lines": _snippet_lines(clip_items) if clip_items else "",
        "context_summary": context_summary,
        "generated_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "item_count": len(all_new_items),
    }
    return report_id, _render_markdown(context)


def save_report(markdown: str, report_id: str, output_dir: str) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"report-{report_id}.md"
    path.write_text(markdown)
    return path


def email_report(markdown: str, report_id: str, industry_name: str, email_cfg: dict):
    if not email_cfg.get("enabled"):
        return
    user = env(email_cfg.get("smtp_user_env", ""))
    password = env(email_cfg.get("smtp_pass_env", ""))
    to = email_cfg.get("to", [])
    if not (user and password and to):
        print("[report] Email enabled but SMTP creds or recipients missing; skipping send.")
        return

    msg = MIMEMultipart()
    msg["From"] = user
    msg["To"] = ", ".join(to)
    msg["Subject"] = f"{industry_name} Weekly Briefing — {report_id}"
    msg.attach(MIMEText(markdown, "plain"))

    try:
        with smtplib.SMTP(email_cfg["smtp_host"], email_cfg["smtp_port"]) as server:
            server.starttls()
            server.login(user, password)
            server.sendmail(user, to, msg.as_string())
        print(f"[report] Emailed to {to}")
    except Exception as e:
        print(f"[report] Failed to send email: {e}")
